import USDCe_ABI from './USDCe_ABI.json'
import USDCe_BYTECODE from './USDCe_bytecode.js'
import USDCe_impl_ABI from './USDCe_impl_ABI.json'
import USDCe_impl_BYTECODE from './USDCe_impl_bytecode.js'

export const USDCe = {
  abi: USDCe_ABI,
  bytecode: USDCe_BYTECODE,
  network: 'mainnet',
  name: 'USDCe',
  address: '0x74c9f2b00581f1b11aa7ff05aa9f608b7389de67',
  unverifiedMethods: [],
  unverifiedInterfaces: [],
  verifiedMethods: [],
  verifiedInterfaces: [],
  proxyDetails: {
    // Proxy contracts: implementation contract may change. In that case, proxy details must be updated
    isProxy: true,
    implementationABI: USDCe_impl_ABI,
    implementationBytecode: USDCe_impl_BYTECODE,
    implementationAddress: '0x40461291347e1ecbb09499f3371d3f17f10d7159',
    unverifiedImplementationMethods: [
      'allowance(address,address)',
      'approve(address,uint256)',
      'balanceOf(address)',
      'decimals()',
      'decreaseAllowance(address,uint256)',
      'increaseAllowance(address,uint256)',
      'mint(address,uint256)',
      'name()',
      'symbol()',
      'totalSupply()',
      'transfer(address,uint256)',
      'transferFrom(address,address,uint256)',
      'owner()',
      'transferOwnership(address)',
      'isMinter(address)',
      'pause()',
      'paused()',
      'unpause()',
      'removeMinter(address)',
      'burn(uint256)'
    ],
    unverifiedImplementationInterfaces: ['ERC20'],
    verifiedImplementationMethods: [
      'CANCEL_AUTHORIZATION_TYPEHASH()',
      'DOMAIN_SEPARATOR()',
      'PERMIT_TYPEHASH()',
      'RECEIVE_WITH_AUTHORIZATION_TYPEHASH()',
      'TRANSFER_WITH_AUTHORIZATION_TYPEHASH()',
      'allowance(address,address)',
      'approve(address,uint256)',
      'authorizationState(address,bytes32)',
      'balanceOf(address)',
      'blacklist(address)',
      'blacklister()',
      'burn(uint256)',
      'cancelAuthorization(address,bytes32,uint8,bytes32,bytes32)',
      'cancelAuthorization(address,bytes32,bytes)',
      'configureMinter(address,uint256)',
      'currency()',
      'decimals()',
      'decreaseAllowance(address,uint256)',
      'increaseAllowance(address,uint256)',
      'initialize(string,string,string,uint8,address,address,address,address)',
      'initializeV2(string)',
      'initializeV2_1(address)',
      'initializeV2_2(address[],string)',
      'isBlacklisted(address)',
      'isMinter(address)',
      'masterMinter()',
      'mint(address,uint256)',
      'minterAllowance(address)',
      'name()',
      'nonces(address)',
      'owner()',
      'pause()',
      'paused()',
      'pauser()',
      'permit(address,address,uint256,uint256,bytes)',
      'permit(address,address,uint256,uint256,uint8,bytes32,bytes32)',
      'receiveWithAuthorization(address,address,uint256,uint256,uint256,bytes32,bytes)',
      'receiveWithAuthorization(address,address,uint256,uint256,uint256,bytes32,uint8,bytes32,bytes32)',
      'removeMinter(address)',
      'rescueERC20(address,address,uint256)',
      'rescuer()',
      'symbol()',
      'totalSupply()',
      'transfer(address,uint256)',
      'transferFrom(address,address,uint256)',
      'transferOwnership(address)',
      'transferWithAuthorization(address,address,uint256,uint256,uint256,bytes32,bytes)',
      'transferWithAuthorization(address,address,uint256,uint256,uint256,bytes32,uint8,bytes32,bytes32)',
      'unBlacklist(address)',
      'unpause()',
      'updateBlacklister(address)',
      'updateMasterMinter(address)',
      'updatePauser(address)',
      'updateRescuer(address)',
      'version()'
    ],
    verifiedImplementationInterfaces: ['ERC20']
  }
}
